name: .NET

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RedisHost: localhost
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      - name: Test
        run: make test
  publish:
    runs-on: ubuntu-latest
    env:
      RedisHost: localhost
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      - name: docker publish
        env:
          NUGET_KEY: ${{secrets.DOCKER_USER}}
        run: |
          make publish
